version: '3'

services:
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    

  # nginx-rtmp:
  #   image: tiangolo/nginx-rtmp
  #   ports:
  #     - 1935:1935
  #     - 8080:80
  #     - 8443:443
  #   environment:
  #     - HTTP_PORT=80
  #     - RTMP_PORT=1935
  #   volumes:
  #     - ./certs:/opt/certs
      # - ./nginx:/etc/nginx

  nginx-rtmp:
    image: nginx
    ports:
      - 1935:1935
      - 8080:80
      - 8443:443
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
    volumes:
      - ./certs:/opt/certs
      # - ./nginx:/etc/nginx

